#@data/values
#@overlay/match-child-defaults missing_ok=True
---
capi:
  cf_api_controllers_client_secret: ""
  cc_username_lookup_client_secret: ""

#! control optional deployment of a database for CF
cf_db:
  admin_password: ""

internal_certificate:
  #! Base64-encoded certificate for the wildcard
  #! subdomain of the system domain (e.g., CN=*.cf-system.svc.cluster.local)
  crt: ""
  #! Base64-encoded private key for the internal certificate
  key: ""
  #! Base64-encoded CA certificate used to sign the internal certifcate
  ca: ""

metric_proxy:
  ca:
    secret_name: "metric-proxy-ca"
    crt: ""
    key: ""
  cert:
    secret_name: "metric-proxy-cert"
    crt: ""
    key: ""

uaa:
 #! client secret for uaa admin client in plain text
  admin_client_secret: ""

  encryption_key:
    #! Plain text passphrase
    passphrase: ""

  jwt_policy:
    #! Plain text private key
    signing_key: ""

  login:
    service_provider:
      #! Plain text private key
      key: ""
      #! Plain text password
      key_password: ""
      #! Plain text certificate
      certificate: ""

  #! Plain text password
  login_secret: ""
