#@ load("@ytt:data", "data")
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: metric-proxy
  namespace: #@ data.values.system_namespace

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metric-proxy
  namespace: #@ data.values.system_namespace
rules:
  - apiGroups: ["*"]
    resources: ["pods", "namespaces"]
    verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metric-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metric-proxy
subjects:
  - kind: ServiceAccount
    name: metric-proxy
    namespace: #@ data.values.system_namespace

