#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.all,expects="1+"
---
jobs:
  #@overlay/match by=overlay.all,expects="1+"
  - plan:
     #@overlay/match by=overlay.index(0)
     #@overlay/insert before=True
     - task: pipeline-revision-info
       config:
        platform: "linux"
        image_resource:
          source:
            repository: busybox
          type: docker-image
        run:
          path: /bin/echo
          args: 
            - "-e"
            - #@ str(data.values.pipeline_revision)