#@ load("@ytt:template", "template")
#@ load("@ytt:yaml", "yaml")
#@ load("/namespaces.star", "system_namespace")
#@ load("/quarks-secret/quarks-secret.star", "quarks_secret_enabled")

#@ if quarks_secret_enabled():

#@ def quarks_secret_uaa_client_credential_template(client_name):
oauth:
  #@yaml/text-templated-strings
  clients:
    (@= client_name @):
      secret: "{{.Values.client_credentials}}"
#@ end

#@ def quarks_secret_uaa_client_credentials(client_name, credential_reference):
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: #@ "uaa-templated-" + credential_reference
  namespace: #@ system_namespace()
spec:
  type: templatedconfig
  secretName: #@ "uaa-" + credential_reference
  request:
    templatedConfig:
      type: helm
      templates:
        client_credentials.yml: #@ yaml.encode(quarks_secret_uaa_client_credential_template(client_name))
      values:
        client_credentials:
          name: #@ credential_reference
          key: "password"
#@ end

#@ def quarks_secret_uaa_cf_admin_user_credential_template():
scim:
  users:
  - "admin|{{.Values.client_credentials}}|admin@admin.tld|first|last|clients.read,cloud_controller.admin,doppler.firehose,network.admin,openid,routing.router_groups.read,routing.router_groups.write,scim.read,scim.write|uaa"
#@ end

#@ def quarks_secret_uaa_cf_admin_user_credentials():
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: "uaa-templated-cf-admin-user-credentials"
  namespace: #@ system_namespace()
spec:
  type: templatedconfig
  secretName: "uaa-cf-admin-user-credentials"
  request:
    templatedConfig:
      type: helm
      templates:
        cf_admin_user_credentials.yml: #@ yaml.encode(quarks_secret_uaa_cf_admin_user_credential_template())
      values:
        client_credentials:
          name: "cf-admin-user-credentials"
          key: "password"
#@ end

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: cf-admin-user-credentials
  namespace: #@ system_namespace()
spec:
  type: password
  secretName: cf-admin-user-credentials

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: uaa-admin-client-credentials
  namespace: #@ system_namespace()
spec:
  type: password
  secretName: uaa-admin-client-credentials

--- #@ template.replace(quarks_secret_uaa_client_credentials("cloud_controller_username_lookup", "cloud-controller-username-lookup-client-secret"))
--- #@ template.replace(quarks_secret_uaa_client_credentials("cf_api_controllers", "cf-api-controllers-client-secret"))
--- #@ template.replace(quarks_secret_uaa_client_credentials("cf_api_backup_metadata_generator", "cf-api-backup-metadata-generator-client-secret"))
--- #@ template.replace(quarks_secret_uaa_client_credentials("admin", "uaa-admin-client-credentials"))
--- #@ template.replace(quarks_secret_uaa_cf_admin_user_credentials())

#@ end
