output "cluster_id" {
  description = "EKS cluster ID"
  value       = module.eks.cluster_id
}

output "kubeconfig" {
  description = "kubectl config as generated by the module"
  value       = module.eks.kubeconfig
  sensitive   = true
}
