#@ load("@ytt:data", "data")

---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: #@ data.values.workloadsNamespace
spec:
  egress:
  - hosts:
    - #@ data.values.systemNamespace + "/*"
