---
# Extract common platform and image_resource details so task configs can be more concise
x-config: &common-task-config
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: relintdockerhubpushbot/cf-for-k8s-ci

resources:
- name: cf-for-k8s-master
  type: git
  icon: github
  source:
    branch: master
    uri: git@github.com:cloudfoundry/cf-for-k8s
    private_key: ((cf_for_k8s_readonly_deploy_key.private_key))

- name: cf-for-k8s-ci
  type: git
  icon: github
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/cf-for-k8s
    private_key: ((cf_for_k8s_readonly_deploy_key.private_key))
    paths:
    - ci/**

- name: cf-for-k8s-last-valid-commit
  type: git
  icon: github
  source:
    branch: last-valid-commit
    uri: git@github.com:cloudfoundry/cf-for-k8s
    private_key: ((cf_for_k8s_readwrite_deploy_key.private_key))

- name: runtime-ci
  type: git
  icon: github
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git

- name: ready-pool
  type: pool
  icon: pool
  source:
    uri: git@github.com:cloudfoundry/relint-ci-pools
    branch: master
    pool: k8s-dev/ready
    private_key: ((relint_ci_pools_readwrite_deploy_key.private_key))

- name: destroy-pool
  type: pool
  icon: pool
  source:
    uri: git@github.com:cloudfoundry/relint-ci-pools
    branch: master
    pool: k8s-dev/destroy
    private_key: ((relint_ci_pools_readwrite_deploy_key.private_key))

jobs:
- name: validate-cf-for-k8s-upgrade
  serial: true
  public: true
  plan:
  - in_parallel:
    - get: cf-for-k8s-last-valid-commit
    - get: cf-for-k8s-master
      trigger: true
    - get: cf-for-k8s-ci
    - get: runtime-ci

  - put: ready-pool
    params:
      acquire: true

  - task: display-cluster-info
    file: cf-for-k8s-ci/ci/tasks/display-gke-cluster-info/task.yml
    input_mapping:
      pool-lock: ready-pool
    params:
      GCP_PROJECT_NAME: ((ci_k8s_gcp_project_name))
      GCP_PROJECT_ZONE: ((ci_k8s_gcp_project_zone))
      GCP_SERVICE_ACCOUNT_JSON: ((ci_k8s_gcp_service_account_json))

  - task: install-cf-last-valid-commit
    file: cf-for-k8s-ci/ci/tasks/install-cf-on-gke/task.yml
    input_mapping:
      pool-lock: ready-pool
      cf-for-k8s: cf-for-k8s-last-valid-commit
    params:
      GCP_SERVICE_ACCOUNT_JSON: ((ci_k8s_gcp_service_account_json))
      GCP_PROJECT_NAME: ((ci_k8s_gcp_project_name))
      GCP_PROJECT_ZONE: ((ci_k8s_gcp_project_zone))
      DOMAIN: k8s-dev.relint.rocks

  - task: push-test-app
    file: cf-for-k8s-ci/ci/tasks/push-test-app/task.yml
    input_mapping:
      cf-for-k8s: cf-for-k8s-last-valid-commit
    params:
      APP_NAME: jp-node-app
      VERIFY_EXISTING_APP: false

  - task: upgrade-cf-to-master
    file: cf-for-k8s-ci/ci/tasks/install-cf-on-gke/task.yml
    input_mapping:
      pool-lock: ready-pool
      cf-for-k8s: cf-for-k8s-master
    params:
      GCP_SERVICE_ACCOUNT_JSON: ((ci_k8s_gcp_service_account_json))
      GCP_PROJECT_NAME: ((ci_k8s_gcp_project_name))
      GCP_PROJECT_ZONE: ((ci_k8s_gcp_project_zone))
      DOMAIN: k8s-dev.relint.rocks
      UPGRADE: true
      UPTIMER: true
      EMIT_UPTIMER_METRICS_TO_WAVEFRONT: true
      WAVEFRONT_API_KEY: ((wavefront_ci_service_account))
      WAVEFRONT_API_ENDPOINT: "https://vmwareprod.wavefront.com/report"
      SOURCE_PIPELINE: upgrade-from-last-valid

  - in_parallel:
    - task: run-smoke-tests
      file: cf-for-k8s-ci/ci/tasks/run-smoke-tests/task.yml
      input_mapping:
        cf-for-k8s: cf-for-k8s-master
      params:
        SMOKE_TEST_SKIP_SSL: true

    - task: verify-existing-app
      file: cf-for-k8s-ci/ci/tasks/push-test-app/task.yml
      params:
        APP_NAME: jp-node-app
        VERIFY_EXISTING_APP: true
      input_mapping:
        cf-for-k8s: cf-for-k8s-master

  - task: delete-cf
    file: cf-for-k8s-ci/ci/tasks/delete-cf/task.yml
    input_mapping:
      pool-lock: ready-pool

  - put: destroy-pool
    params:
      add: ready-pool

  - put: ready-pool
    params:
      remove: ready-pool

  on_failure:
    task: job-failure
    config:
      << : *common-task-config
      run:
        path: /bin/bash
        args:
        - -c
        - |
          echo "Upgrade has failed."
          echo "If appropriate, the last valid commit can be updated to HEAD of master via the 'update-last-valid-commit-to-head-of-master' job."

- name: update-last-valid-commit-to-head-of-master
  serial: true
  public: true
  plan:
  - in_parallel:
    - get: cf-for-k8s-last-valid-commit
    - get: cf-for-k8s-master

  - put: cf-for-k8s-last-valid-commit
    params:
      repository:
        cf-for-k8s-master
