---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: config/_ytt_lib
  contents:
  - path: github.com/GoogleCloudPlatform/metacontroller
    git:
      url: https://github.com/GoogleCloudPlatform/metacontroller
      ref: v0.4.0
    includePaths:
    - manifests/*
  - path: github.com/cloudfoundry/cf-k8s-networking
    git:
      url: https://github.com/cloudfoundry/cf-k8s-networking
      ref: eb3bad0ae52316cf992a5da1fcdec15715f5ab07
    includePaths:
    - cfroutesync/crds/**/*
    - config/cfroutesync/**/*
    - config/istio-generated/**/*
  - path: github.com/cloudfoundry/capi-k8s-release
    git:
      url: https://github.com/cloudfoundry/capi-k8s-release
      ref: 1bc5ea5eac9359af22fb2088c21a27f5a4b356aa
    includePaths:
    - templates/**/*
    - values.yml
  - path: github.com/cloudfoundry/cf-k8s-logging
    git:
      url: https://github.com/cloudfoundry/cf-k8s-logging
      ref: c93a12170b5bd58eeffd195d07fcb87af069f684
    includePaths:
    - config/**/*
  - path: github.com/cloudfoundry/uaa
    git:
      url: https://github.com/cloudfoundry/uaa
      ref: 5f3af8a7b158c77320c04b45efae99c936ad0a7d
    includePaths:
    - k8s/templates/**/*
    - k8s/values/default-values.yml
  - path: github.com/pivotal/kpack
    githubRelease:
      slug: pivotal/kpack
      tag: v0.0.6
      disableAutoChecksumValidation: true
    includePaths:
    - release-0.0.6.yaml
  - path: docker-registry
    manual: {}
  - path: eirini
    manual: {}
  - path: minio
    manual: {}
  - path: postgres
    manual: {}
# When adding a helm chart to our set of components:
# 1. Find the chart you need from https://hub.helm.sh/charts/stable
# 2. Note the latest (or desired) version from the "Chart Versions" section on the right.
# 3. Navigate to the corresponding directory of https://github.com/helm/charts/tree/master/stable
# 4. Look at the history or blame log of the Chart.yaml file to find when the version was bumped to the version you found earlier.
# 5. The SHA of the commit that bumped the version will be the SHA you use as the 'ref' of the git section below.
- path: build/minio/_vendir
  contents:
  - path: .
    git:
      url: https://github.com/helm/charts
      ref: 21546e62d205fe6d197a8f920532d9b78b67a71f # version: 5.0.6
    includePaths:
    - stable/minio/**/*

- path: build/docker-registry/_vendir
  contents:
  - path: .
    git:
      url: https://github.com/helm/charts
      # chart version: 1.9.1
      # app version: 2.7.1
      ref: 2b1e12f5f748a69a1429a1bb015bc34f3124c4e2
    includePaths:
    - stable/docker-registry/**/*
- path: build/eirini/_vendir
  contents:
  - path: .
    githubRelease:
      slug: cloudfoundry-incubator/eirini-release
      tag: v1.2.0
      disableAutoChecksumValidation: true
      unpackArchive:
        path: eirini.tgz
