---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
- path: config/_ytt_lib
  contents:
  - path: github.com/GoogleCloudPlatform/metacontroller
    git:
      url: https://github.com/GoogleCloudPlatform/metacontroller
      ref: v0.4.0
    includePaths:
    - manifests/*
  - path: github.com/cloudfoundry/cf-k8s-networking
    git:
      url: https://github.com/cloudfoundry/cf-k8s-networking
      ref: 5efa247a8f46953e9cb88f71b3ef47c2cdd39385
    includePaths:
    - cfroutesync/crds/**/*
    - config/cfroutesync/**/*
    - config/istio-generated/**/*
  - path: github.com/cloudfoundry/capi-k8s-release
    git:
      url: https://github.com/cloudfoundry/capi-k8s-release
      ref: 9e7bb239bc6c9ac8e633d29ad181832e90251a83
    includePaths:
    - templates/**/*
    - values.yml
  - path: github.com/cloudfoundry/cf-k8s-logging
    git:
      url: https://github.com/cloudfoundry/cf-k8s-logging
      ref: 8ec400d0d457862b78a19a59322c439ef51835e9
    includePaths:
    - config/**/*
  - path: github.com/cloudfoundry/uaa
    git:
      url: https://github.com/cloudfoundry/uaa
      ref: 1c19ffc2697441824d2e98e31210a82e1fbc0ac1 # v74.15.0
    includePaths:
    - k8s/templates/**/*
    - k8s/values/default-values.yml
  - path: github.com/pivotal/kpack
    githubRelease:
      slug: pivotal/kpack
      tag: v0.0.6
      disableAutoChecksumValidation: true
    includePaths:
    - release-0.0.6.yaml
  - path: eirini
    manual: {}
  - path: minio
    manual: {}
  - path: postgres
    manual: {}
# When adding a helm chart to our set of components:
# 1. Find the chart you need from https://hub.helm.sh/charts/stable
# 2. Note the latest (or desired) version from the "Chart Versions" section on the right.
# 3. Navigate to the corresponding directory of https://github.com/helm/charts/tree/master/stable or related repo
# 4. Look at the history or blame log of the Chart.yaml file to find when the version was bumped to the version you found earlier.
# 5. The SHA of the commit that bumped the version will be the SHA you use as the 'ref' of the git section below.
- path: build/minio/_vendir
  contents:
  - path: .
    git:
      url: https://github.com/helm/charts
      ref: 21546e62d205fe6d197a8f920532d9b78b67a71f # version: 5.0.6
    includePaths:
    - stable/minio/**/*

- path: build/eirini/_vendir
  contents:
  - path: .
    githubRelease:
      slug: cloudfoundry-incubator/eirini-release
      tag: v1.4.0
      disableAutoChecksumValidation: true
      unpackArchive:
        path: eirini.tgz
- path: build/postgres/_vendir
  contents:
  - path: .
    git:
      url: https://github.com/bitnami/charts
      ref: a4df45b81a9d0a7862f043765bc13bc875bdad96 # version: 8.6.4
    includePaths:
    - bitnami/postgresql/**/*
