#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cc-kpack-registry-service-account
  namespace: #@ data.values.staging_namespace
secrets:
  - name: cc-kpack-registry-auth-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: cc-kpack-registry-auth-secret
  namespace: #@ data.values.staging_namespace
  annotations:
    build.pivotal.io/docker: #@ data.values.kpack.registry.hostname
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.kpack.registry.username
  password: #@ data.values.kpack.registry.password
