#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")
#@ load("secrets.lib.yml","shared_config_volumes", "shared_config_volume_mounts", "ccng_config_mount_path", "ccng_secrets_mount_path")
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ccdb-migrate
  namespace: #@ data.values.system_namespace
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
spec:
  backoffLimit: 6
  template:
    spec:
      containers:
      - name: run-migrations
        image: #@ data.values.images.ccng
        imagePullPolicy: Always
        command: [ "/cnb/process/migrate" ]
        env:
        - name: CLOUD_CONTROLLER_NG_CONFIG
          value: #@ ccng_config_mount_path
        - name: CLOUD_CONTROLLER_NG_SECRETS
          value: #@ ccng_secrets_mount_path
        volumeMounts:
        - #@ template.replace(shared_config_volume_mounts())
        #@ if/end data.values.ccdb.ca_cert:
        - name: database-ca-cert
          mountPath: /config/database/certs
      restartPolicy: OnFailure
      volumes:
      - #@ template.replace(shared_config_volumes())
      #@ if/end data.values.ccdb.ca_cert:
      - name: database-ca-cert
        secret:
          secretName: database-ca-cert

