#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cf-api-controllers-service-account
  namespace: #@ data.values.system_namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-api-controllers-service-account-kpack-builds-reader
  namespace: #@ data.values.staging_namespace
subjects:
  - kind: ServiceAccount
    name: cf-api-controllers-service-account
    namespace: #@ data.values.system_namespace
roleRef:
  kind: ClusterRole
  name: "cf:kpack-builds-informer"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-api-controllers-service-account-service-accounts-secrets-fetcher
  namespace: #@ data.values.staging_namespace
subjects:
  - kind: ServiceAccount
    name: cf-api-controllers-service-account
    namespace: #@ data.values.system_namespace
roleRef:
  kind: ClusterRole
  name: "cf:service-accounts-secrets-fetcher"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-api-controllers-service-account-statefulsets-updater
  namespace: #@ data.values.workloads_namespace
subjects:
  - kind: ServiceAccount
    name: cf-api-controllers-service-account
    namespace: #@ data.values.system_namespace
roleRef:
  kind: ClusterRole
  name: "cf:statefulsets-updater"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cf-api-controllers-service-account-periodicsyncs-admin
subjects:
  - kind: ServiceAccount
    name: cf-api-controllers-service-account
    namespace: #@ data.values.system_namespace
roleRef:
  kind: ClusterRole
  name: "cf:periodicsyncs-admin"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cf-api-controllers-service-account-routes-admin
subjects:
  - kind: ServiceAccount
    name: cf-api-controllers-service-account
    namespace: #@ data.values.system_namespace
roleRef:
  kind: ClusterRole
  name: "cf:routes-admin"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "cf:kpack-builds-informer"
rules:
  - apiGroups:
      - kpack.io
    resources:
      - builds
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "cf:service-accounts-secrets-fetcher"
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "cf:statefulsets-updater"
rules:
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - list
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: "cf:periodicsyncs-admin"
rules:
  - apiGroups:
      - apps.cloudfoundry.org
    resources:
      - periodicsyncs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps.cloudfoundry.org
    resources:
      - periodicsyncs/status
    verbs:
      - get
      - patch
      - update
