#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cf-api-worker-service-account
  namespace: #@ data.values.system_namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-api-worker-service-account-cf-routes-admin
  namespace: #@ data.values.workloads_namespace
subjects:
  - kind: ServiceAccount
    name: cf-api-worker-service-account
    namespace: #@ data.values.system_namespace
roleRef:
  kind: ClusterRole
  name: "cf:routes-admin"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-api-worker-service-account-kpack-builds-admin
  namespace: #@ data.values.staging_namespace
subjects:
  - kind: ServiceAccount
    name: cf-api-worker-service-account
    namespace: #@ data.values.system_namespace
roleRef:
  kind: ClusterRole
  name: "cf:kpack-builds-admin"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-api-worker-service-account-kpack-builder-admin
  namespace: #@ data.values.staging_namespace
subjects:
  - kind: ServiceAccount
    name: cf-api-worker-service-account
    namespace: #@ data.values.system_namespace
roleRef:
  kind: ClusterRole
  name: "cf:kpack-builder-admin"
  apiGroup: rbac.authorization.k8s.io
