#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cf-api-server-service-account
  namespace: #@ data.values.system_namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-api-server-service-account-cf-routes-admin
  namespace: #@ data.values.workloads_namespace
subjects:
  - kind: ServiceAccount
    name: cf-api-server-service-account
    namespace: #@ data.values.system_namespace
roleRef:
  kind: ClusterRole
  name: "cf:routes-admin"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-api-server-service-account-kpack-builds-admin
  namespace: #@ data.values.staging_namespace
subjects:
  - kind: ServiceAccount
    name: cf-api-server-service-account
    namespace: #@ data.values.system_namespace
roleRef:
  kind: ClusterRole
  name: "cf:kpack-builds-admin"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-api-server-service-account-kpack-builder-admin
  namespace: #@ data.values.staging_namespace
subjects:
  - kind: ServiceAccount
    name: cf-api-server-service-account
    namespace: #@ data.values.system_namespace
roleRef:
  kind: ClusterRole
  name: "cf:kpack-builder-admin"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "cf:routes-admin"
rules:
  - apiGroups:
      - networking.cloudfoundry.org
    resources:
      - routes
    verbs:
      - create
      - get
      - update
      - delete
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "cf:kpack-builds-admin"
rules:
  - apiGroups:
      - kpack.io
    resources:
      - images
    verbs:
      - create
      - get
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "cf:kpack-builder-admin"
rules:
  - apiGroups:
      - kpack.io
    resources:
      - builders
      - builders/status
    verbs:
      - get
      - create
      - update
      - delete
