#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")
#@ load("secrets.lib.yml","shared_config_volumes", "shared_config_volume_mounts", "ccng_config_mount_path", "ccng_secrets_mount_path")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-api-clock
  namespace: #@ data.values.system_namespace
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cf-api-clock
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cf-api-clock
    spec:
      #@ if/end data.values.imagePullSecrets:
      imagePullSecrets: #@ data.values.imagePullSecrets
      containers:
        - name: cf-api-clock
          image: #@ data.values.images.ccng
          imagePullPolicy: Always
          workingDir: "/cloud_controller_ng"
          command: ["/usr/local/bin/bundle"]
          args: ["exec", "rake", "clock:start"]
          env:
          - name: CLOUD_CONTROLLER_NG_CONFIG
            value: #@ ccng_config_mount_path
          - name: CLOUD_CONTROLLER_NG_SECRETS
            value: #@ ccng_secrets_mount_path
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 4446
            periodSeconds: 3
          volumeMounts:
          - #@ template.replace(shared_config_volume_mounts())
          #@ if/end data.values.ccdb.ca_cert:
          - name: database-ca-cert
            mountPath: /config/database/certs
          #@ if/end data.values.eirini.serverCerts.secretName:
          - name: eirini-certs
            mountPath: /config/eirini/certs
      volumes:
      - #@ template.replace(shared_config_volumes())
      #@ if/end data.values.eirini.serverCerts.secretName:
      - name: eirini-certs
        secret:
          secretName: #@ data.values.eirini.serverCerts.secretName
      #@ if/end data.values.ccdb.ca_cert:
      - name: database-ca-cert
        secret:
          secretName: database-ca-cert
