#@ load("@ytt:data","data")
#@ load("@ytt:yaml","yaml")
#@ load("secrets.lib.yml", "ccng_secrets")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-controller-ng-secrets-yaml
  namespace: #@ data.values.system_namespace
  annotations:
    kapp.k14s.io/versioned: ""
data:
  secrets.yml: #@ yaml.encode(ccng_secrets())
