#@ load("@ytt:data","data")

#@ def shared_config_volumes():
- name: cloud-controller-ng-yaml
  configMap:
    name: cloud-controller-ng-yaml
- name: cloud-controller-ng-secrets-yaml
  configMap:
    name: cloud-controller-ng-secrets-yaml
- name: cf-api-db-password
  secret:
    secretName: #@ data.values.ccdb.password_secret_name
- name: cf-api-db-encryption-key
  secret:
    secretName: #@ data.values.ccdb.encryption_key_secret_name
- name: cf-api-username-lookup-client-secret
  secret:
    secretName: #@ data.values.uaa.clients.cloud_controller_username_lookup.secret_name
- name: cf-api-blobstore-secret-access-key
  secret:
    secretName: #@ data.values.blobstore.secret_access_key_secret_name
#@ end

---

#@ ccng_config_mount_path = "/config/cloud_controller_ng.yml"
#@ ccng_secrets_mount_path = "/config/secrets.yml"
#@ ccdb_password_mount_path = "/etc/cf-api/ccdb_password"
#@ ccdb_encryption_key_mount_path = "/etc/cf-api/ccdb_encryption_key"
#@ cf_api_username_lookup_client_secret_mount_path = "/etc/cf-api/username-lookup-client-secret"
#@ cf_api_blobstore_secret_access_key_mount_path = "/etc/cf-api/blobstore/secret-access-key"

---

#@ def shared_config_volume_mounts():
- name: cloud-controller-ng-yaml
  mountPath: #@ ccng_config_mount_path
  subPath: cloud_controller_ng.yml

- name: cloud-controller-ng-secrets-yaml
  mountPath: #@ ccng_secrets_mount_path
  subPath: secrets.yml

#! secrets for credentials used in config

- name: cf-api-db-password
  mountPath: #@ ccdb_password_mount_path

- name: cf-api-db-encryption-key
  mountPath: #@ ccdb_encryption_key_mount_path

- name: cf-api-username-lookup-client-secret
  mountPath: #@ cf_api_username_lookup_client_secret_mount_path

- name: cf-api-blobstore-secret-access-key
  mountPath: #@ cf_api_blobstore_secret_access_key_mount_path
#@ end

---

#@ def ccng_secrets():
cloud_controller_username_lookup_client_secret:  #@ cf_api_username_lookup_client_secret_mount_path + "/password"
db:
  database:
    password: #@ ccdb_password_mount_path + "/password"

db_encryption_key: #@ ccdb_encryption_key_mount_path + "/password"
database_encryption:
  keys:
    encryption_key_0: #@ ccdb_encryption_key_mount_path + "/password"

resource_pool:
  fog_connection:
    aws_secret_access_key: #@ cf_api_blobstore_secret_access_key_mount_path + "/password"
packages:
  fog_connection:
    aws_secret_access_key:  #@ cf_api_blobstore_secret_access_key_mount_path + "/password"
droplets:
  fog_connection:
    aws_secret_access_key:  #@ cf_api_blobstore_secret_access_key_mount_path + "/password"
buildpacks:
  fog_connection:
    aws_secret_access_key:  #@ cf_api_blobstore_secret_access_key_mount_path + "/password"
#@ end
