---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-for-k8s-ci

inputs:
  # Used to determine the config for the kind cluster
- name: cf-for-k8s
  # Used as the task file source
- name: cf-for-k8s-ci
- name: terraform

params:
  GCP_KEY: ~
  GCP_PROJECT_NAME: ~
  VERSION_SELECTOR: ~

run:
  path: cf-for-k8s-ci/ci/tasks/create-kind-cluster/task.sh
