#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"Store"})
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/change-group.kpack-resources: "cf-for-k8s.cloudfoundry.org/kpack-resources"

#@overlay/match by=overlay.subset({"kind":"Stack"})
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/change-group.kpack-resources: "cf-for-k8s.cloudfoundry.org/kpack-resources"

#@overlay/match by=overlay.subset({"kind":"CustomBuilder"})
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/change-rule.kpack-resources: "upsert after upserting cf-for-k8s.cloudfoundry.org/kpack-resources"
