
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
  - name: registry-buddy
  - name: cf-for-k8s-ci

params: {}

run:
  path: cf-for-k8s-ci/ci/tasks/cake/run-registry-buddy-unit-tests.sh
