---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: pivotalcfreleng/tas-for-k8s-ci

inputs:
- name: image
- name: source-repository

outputs:
- name: labeled-image

run:
  path: bash
  args:
  - -euc
  - deplab --image-tar image/image.tar --git source-repository --output-tar "labeled-image/image.tar"
