#!/usr/bin/env bash
set -euo pipefail

: "${STALE_AFTER_DAYS:?}"

pushd pool-repo > /dev/null

stale_starting_in_epoch="$(( $(date "+%s") - STALE_AFTER_DAYS * 60 * 60 * 24 ))"

mapfile -t claimed_ready_locks < <(ls k8s-dev/ready/claimed/*)

for claimed_ready_lock in "${claimed_ready_locks[@]}"; do
  locked_since_in_epoch="$(git log -1 --pretty="format:%ct" -- "$claimed_ready_lock")"

  if (( locked_since_in_epoch <= stale_starting_in_epoch )); then
    git mv "$claimed_ready_lock" k8s-dev/destroy/unclaimed
  fi
done

git config user.email "cf-release-integration@pivotal.io"
git config user.name "relint-ci"
git diff-index --quiet HEAD || git commit -m "Schedule stale claimed environments for destruction"

popd
