#@ load("@ytt:data", "data")
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ccdb-migrate
  namespace: #@ data.values.system_namespace
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: run-migrations
        image: #@ data.values.images.ccng
        imagePullPolicy: Always
        command: ['bundle', 'exec', 'rake', 'db:setup_database']
        volumeMounts:
        - name: cloud-controller-ng-yaml
          mountPath: /config
      restartPolicy: Never
      volumes:
      - name: cloud-controller-ng-yaml
        configMap:
          name: cloud-controller-ng-yaml
