---
#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")

#! Useful command
#! cat <(awk '-F|' '$4 == " Yes " { printf("%s\n", gensub(/\s+/, "", "g", $2)) }' docs/platform_operators/deploy-parameters.md) docs/platform_operators/required-parameters.txt | sort -u
#! 'docs/platform_operators/required-parameters.txt' contents come from story 174981087

#@ def is_missing(data_values, param):
#@     parts = param.split('.')
#@     obj = data_values
#@     for p in parts[0:-1]:
#@         obj = getattr(obj, p, None)
#@     end
#@     return not hasattr(obj, parts[-1])
#@ end
#@
#@ def check_missing_required_parameters(data_values):
#@     required_parameters = '''\
#@ app_domains
#@ app_registry.hostname
#@ app_registry.password
#@ app_registry.repository_prefix
#@ app_registry.username
#@ blobstore.secret_access_key
#@ capi.database.adapter
#@ capi.database.encryption_key
#@ capi.database.host
#@ capi.database.name
#@ capi.database.password
#@ capi.database.port
#@ capi.database.user
#@ cc_username_lookup_client_secret
#@ cf_admin_password
#@ cf_api_controllers_client_secret
#@ cf_db.admin_password
#@ gateway.https_only
#@ internal_certificate.ca
#@ internal_certificate.crt
#@ internal_certificate.key
#@ system_certificate.ca
#@ system_certificate.crt
#@ system_certificate.key
#@ system_domain
#@ uaa.database.adapter
#@ uaa.database.admin_client_secret
#@ uaa.database.host
#@ uaa.database.name
#@ uaa.database.password
#@ uaa.database.port
#@ uaa.database.user
#@ uaa.encryption_key.passphrase
#@ uaa.jwt_policy.signing_key
#@ uaa.login.login_secret
#@ uaa.login.service_provider.certificate
#@ uaa.login.service_provider.key
#@ workloads_certificate.ca
#@ workloads_certificate.crt
#@ workloads_certificate.key'''.split("\n")
#@     missing_parameters = [param for param in required_parameters if is_missing(data_values, param)]
#@     if len(missing_parameters) > 0:
require_parameter_check: #@ assert.fail("The following required data.values parameters are missing: %s" % (missing_parameters,))
#@     end
#@ end
#@
#@ check_missing_required_parameters(data.values)
