---
#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")

#@ def check_top_level_params(data_values, params):
#@     return [x for x in params if not hasattr(data_values, x)]
#@ end
#@
#@ def check_inner_params(data_values, params):
#@     missing_parameters = []
#@     for key, param_list in params:
#@         obj = getattr(data_values, key, None)
#@         missing_parameters += ["%s.%s" % (key, param) for param in param_list if not hasattr(obj, param)]
#@     end
#@     return missing_parameters
#@ end
#@
#@ def check_inner2_params(data_values, params):
#@     missing_parameters = []
#@     for key1, key2, param_list in params:
#@         obj = getattr(getattr(data_values, key1, None), key2, None)
#@         missing_parameters += ["%s.%s.%s" % (key1, key2, param) for param in param_list if not hasattr(obj, param)]
#@     end
#@     return missing_parameters
#@ end
#@
#! Useful command to get the default values:
#! awk '-F|' '$4 == " Yes " { printf("%s\n", gensub(/\s+/, "", "g", $2)) }' docs/platform_operators/deploy-parameters.md
#!
#@ def check_missing_required_parameters(data_values):
#@     top_level_params = ['system_domain', 'app_domains', 'cf_admin_password']
#@     required_inner_params = [['system_certificate', ['crt', 'key', 'ca']],['workloads_certificate', ['crt', 'key', 'ca']],['gateway', ['https_only']],['app_registry', ['hostname', 'repository_prefix', 'username', 'password']],]
#@     require_db_params = [['capi', 'database', ['adapter', 'encryption_key', 'host', 'port', 'user', 'password', 'name']],['uaa', 'database', ['adapter', 'host', 'port', 'user', 'password', 'name']]]
#@
#@     missing_parameters = check_top_level_params(data_values, top_level_params)
#@     missing_parameters += check_inner_params(data_values, required_inner_params)
#@     missing_parameters += check_inner2_params(data_values, require_db_params)
#@
#@     if len(missing_parameters) > 0:
     require_parameter_check: #@ assert.fail("The following required data.values parameters are missing: %s" % (missing_parameters,))
#@     end
#@ end
#@
#@
#@ check_missing_required_parameters(data.values)
