---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
metadata:
  name: "kapp-config"
rebaseRules:
- paths:
  - [metadata, annotations]
  - [webhooks, {allIndexes: true}, rules]
  - [webhooks, {allIndexes: true}, namespaceSelector]
  - [webhooks, {allIndexes: true}, clientConfig, service, path]
  - [webhooks, {allIndexes: true}, sideEffects]
  - [webhooks, {allIndexes: true}, timeoutSeconds]

  type: copy
  sources: [new, existing]
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: admissionregistration.k8s.io/v1beta1
      kind: MutatingWebhookConfiguration
      name: resource.webhook.kpack.pivotal.io
