#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata":{"name": "uaa"}})
---

#! kapp deploy log-cache after UAA
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/change-group: cf-for-k8s.cloudfoundry.org/uaa
#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name": "log-cache"}})
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/change-rule: "upsert after upserting cf-for-k8s.cloudfoundry.org/uaa"
