FROM bash:latest

# deplab
RUN wget \
	https://github.com/vmware-tanzu/dependency-labeler/releases/download/1.5.0-build.3/deplab-linux-amd64 -O /usr/local/bin/deplab && \
    chmod +x /usr/local/bin/deplab
