#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: #@ data.values.metric_proxy.cert.secret_name
  namespace: #@ data.values.system_namespace
data:
  tls.crt: #@ data.values.metric_proxy.cert.crt
  tls.key: #@ data.values.metric_proxy.cert.key

---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: #@ data.values.metric_proxy.ca.secret_name
  namespace: #@ data.values.system_namespace
data:
  tls.crt: #@ data.values.metric_proxy.ca.crt
  tls.key: #@ data.values.metric_proxy.ca.key

