---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-for-k8s-ci
inputs:
  - name: cf-for-k8s-ci
outputs:
  - name: tf-vars-s3
params:
  AWS_ACCESS_KEY_ID: ~
  AWS_SECRET_ACCESS_KEY: ~
  AWS_REGION: ~
run:
  path: cf-for-k8s-ci/ci/tasks/create-s3-tf-vars-file/task.sh
