#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
system_domain: #@ data.values.system_domain
database_hostname: #@ data.values.database_hostname
system_namespace: cf-system

system_certificate:
  crt: #@ data.values.system_certificate.crt
  key: #@ data.values.system_certificate.key
  ca: #@ data.values.system_certificate.ca

capi:
  image:
    repository: #@ data.values.images.capi
  nginx:
    image:
      repository: #@ data.values.images.nginx

  system_domain: #@ data.values.system_domain
  app_domains: #@ data.values.app_domains

  ccdb:
    adapter: #@ data.values.capi.database.adapter
    host: #@ data.values.capi.database.host
    port: #@ data.values.capi.database.port
    user: #@ data.values.capi.database.user
    password: #@ data.values.capi.database.password
    database: #@ data.values.capi.database.name

  uaa:
    clients:
      cloud_controller_username_lookup:
        secret: #@ data.values.uaa.admin_client_secret
uaa:
  image:
    repository: #@ data.values.images.uaa

  system_domain: #@ data.values.system_domain

  admin_client_secret: #@ data.values.uaa.admin_client_secret
  cf_admin_password: #@ data.values.cf_admin_password

  certificate:
    crt: #@ data.values.uaa.certificate.crt
    key: #@ data.values.uaa.certificate.key

  nats:
    image:
      repository: #@ data.values.images.nats
      tag: latest

  doppler:
    image:
      repository: #@ data.values.images.doppler
      tag: latest

    tls:
      ca: #@ data.values.system_certificate.ca
      cert: #@ data.values.doppler.tls.crt
      key: #@ data.values.doppler.tls.key

  opi:
    tls:
      ca: #@ data.values.system_certificate.ca
      cert: #@ data.values.eirini.tls.crt
      key: #@ data.values.eirini.tls.key

    namespace: #@ data.values.workloads_namespace
