apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "uaa-k8srelease.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "uaa-k8srelease.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "uaa-k8srelease.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
      - name: generate-keystore
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: keyfile
            value: "/var/run/secrets/uaa/uaa.key"
          - name: crtfile
            value: "/var/run/secrets/uaa/uaa.crt"
          - name: keystore_pkcs12
            value: "/var/run/secrets/keystore.pkcs12"
          - name: password
            value: "k0*l*s3cur1tyr0ck$"
        command: ['/bin/bash']
        args: ['-c', "openssl pkcs12 -export -name uaa_ssl_cert -inkey $keyfile -in $crtfile -out $keystore_pkcs12 -password pass:$password"]
        volumeMounts:
          - name: keystore-volume
            mountPath: /var/run/secrets
          - name: uaa-certs
            mountPath: /var/run/secrets/uaa
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8443
            - containerPort: 8080
              name: uaa-http
          # Wait 10 minutes for the container to start correctly
          readinessProbe:
            httpGet:
              path: /healthz
              port: uaa-http
            failureThreshold: 60
            periodSeconds: 10
          # After startup, check for liveness every 10 seconds
          livenessProbe:
            httpGet:
              path: /healthz
              port: uaa-http
            failureThreshold: 2
            periodSeconds: 10
            initialDelaySeconds: 600
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: uaa
            mountPath: /workspace/uaa.yml
            subPath: uaa.yml
          - name: keystore-volume
            mountPath: /var/run/secrets
          - name: logs
            mountPath: /workspace/logs
          - name: tomcat-config
            mountPath: /layers/org.cloudfoundry.identity.tomcat/catalina-base/conf/server.xml
            subPath: server.xml
          env:
            - name: CLOUDFOUNDRY_CONFIG_PATH
              value: /workspace
            - name: CLOUDFOUNDRY_LOG_PATH
              value: /workspace/logs
            - name: CATALINA_OPTS
              value: "-Xmx768m -XX:MaxMetaspaceSize=256m"
      volumes:
        - name: keystore-volume
          emptyDir: {}
        - name: uaa-certs
          secret:
            secretName: uaa-certs
        - name: uaa
          configMap:
            name: uaa
        - name: logs
          emptyDir: {}
        - name: tomcat-config
          configMap:
            name: uaa-tomcat-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
