#@ load("@ytt:data", "data")

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: routecontroller
  namespace: #@ data.values.systemNamespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: routecontroller
subjects:
- kind: ServiceAccount
  name: routecontroller
  namespace: #@ data.values.systemNamespace
