#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if data.values.enable_automount_service_account_token:
#! Patch service accounts to enable automount
#!   - Kind does not support setting it to false right now

#@overlay/match by=overlay.subset({"kind":"ServiceAccount", "metadata": {"name":"uaa"}}),expects="0+"
---
#@overlay/match missing_ok=True
#@overlay/replace
automountServiceAccountToken: true
#@ end
