#@ load("@ytt:data", "data")

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: routecontroller
  namespace: #@ data.values.systemNamespace
  labels:
    app.kubernetes.io/name: routecontroller
    app.kubernetes.io/component: cf-networking
    app.kubernetes.io/part-of: cloudfoundry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: routecontroller
subjects:
- kind: ServiceAccount
  name: routecontroller
  namespace: #@ data.values.systemNamespace
