#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: routecontroller
  namespace: #@ data.values.systemNamespace
  labels:
    app.kubernetes.io/name: routecontroller
    app.kubernetes.io/component: cf-networking
    app.kubernetes.io/part-of: cloudfoundry
