#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")
#@ load("/quarks-secret/quarks-secret.star", "quarks_secret_enabled")

#@ if quarks_secret_enabled():
--- #@ template.replace(library.get("quarks-secret").eval())
#@ end
